include:
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: &include_ref 'de411f9f6334ec67972cee98af4b4db731469225'
    file: '/blocks/docker.yml'
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: *include_ref
    file: '/blocks/python.yml'

variables:
  MAJOR_VERSION: "1"
  MINOR_VERSION: "4"

default:
  tags:
  # Target running steps on the Analytics Gitlab runners.
  - analytics
  - dev

stages:
  - build
  - test
  - publish

build_push_image:
  # Publish an image to Artifactory even though it's strictly needed elsewhere, just to aid
  # the build process and mirror local with CICD.
  extends: .doit_build_docker_image
  stage: build

pre_commit_check:
  extends: .run_doit_pre_commit_check
  stage: test

publish_library:
  extends: .build_publish_py_library
  stage: publish
